In [2]:
import numpy as np

## Stacking together two array:

In [3]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [4]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

## Split

In [8]:
a = np.arange(30). reshape(2,15)

In [9]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [10]:
result = np.hsplit(a,3)

In [11]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [16]:
result = np.vsplit(a,2)

In [17]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

## Condition handle using numpy

In [20]:
a = np.arange(12).reshape(3,4)

In [21]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
b = a >= 4

In [26]:
b

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
a[b]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a[b]=-1

In [29]:
a

array([[ 0,  1,  2,  3],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

## Looping numpy array and Flatten

In [7]:
a = np.arange(12).reshape(3,4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
for row in a.flatten():
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


## nditer() for flatten

In [46]:
for x in np.nditer(a,order="C"): # C means row-row(C order)
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [47]:
for x in np.nditer(a,order="F"): # F means column-column(Fortan order)
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [51]:
for x in np.nditer(a,order="F", flags=["external_loop"]): # added external loop
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [52]:
for x in np.nditer(a,order="C", flags=["external_loop"]): # added external loop
    print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...] = x*x
    print(x)

0
1
4
9
16
25
36
49
64
81
100
121


In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
b = np.arange(3,15,4).reshape(3,1)

In [4]:
b

array([[ 3],
       [ 7],
       [11]])

In [10]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
